export const CATEGORY_META = {
  All:        { emoji: '🍽️', color: '#F5E6D3' },
  Cupcakes:   { emoji: '🧁', color: '#F7C8C8' },
  Cakes:      { emoji: '🎂', color: '#A8C686' },
  Cookies:    { emoji: '🍪', color: '#F5E6D3' },
  Bread:      { emoji: '🍞', color: '#E8D5B0' },
  Cheesecake: { emoji: '🥧', color: '#F0E0F0' },
  Pastries:   { emoji: '🥐', color: '#D5E8F0' },
}

export const SAMPLE_RECIPES = [
  {
    id: 'sample-1',
    title: 'Fluffy Vanilla Cupcakes',
    category: 'Cupcakes',
    image_url: null,
    description: 'Light and airy cupcakes with silky buttercream frosting. Perfect for any celebration!',
    time_minutes: 40,
    difficulty: 'Easy',
    user_id: 'sample',
    created_at: new Date().toISOString(),
    ingredients: [
      '1½ cups all-purpose flour',
      '1 cup granulated sugar',
      '½ cup unsalted butter, softened',
      '2 large eggs',
      '½ cup whole milk',
      '2 tsp pure vanilla extract',
      '1½ tsp baking powder',
      '¼ tsp salt',
    ],
    instructions: [
      'Preheat oven to 350°F (175°C) and line a 12-cup muffin tin with paper liners.',
      'Beat butter and sugar together until light and fluffy, about 3 minutes.',
      'Add eggs one at a time, beating well after each addition.',
      'Mix in vanilla extract until combined.',
      'Alternately add flour mixture and milk, starting and ending with flour — mix until just combined.',
      'Fill cups ⅔ full and bake 20-22 minutes until a toothpick comes out clean.',
      'Cool completely on a wire rack before frosting with your favourite buttercream.',
    ],
  },
  {
    id: 'sample-2',
    title: 'Classic Chocolate Layer Cake',
    category: 'Cakes',
    image_url: null,
    description: 'Rich, moist chocolate cake with decadent ganache. The ultimate crowd-pleaser.',
    time_minutes: 75,
    difficulty: 'Medium',
    user_id: 'sample',
    created_at: new Date().toISOString(),
    ingredients: [
      '2 cups all-purpose flour',
      '2 cups granulated sugar',
      '¾ cup unsweetened cocoa powder',
      '2 tsp baking soda',
      '1 tsp salt',
      '2 large eggs',
      '1 cup buttermilk',
      '1 cup strong hot coffee',
      '½ cup vegetable oil',
      '1 tsp vanilla extract',
    ],
    instructions: [
      'Preheat oven to 350°F. Grease and flour two 9-inch round pans.',
      'Whisk together all dry ingredients in a large bowl.',
      'In another bowl, mix eggs, buttermilk, coffee, oil, and vanilla.',
      'Pour wet ingredients into dry and mix until smooth — batter will be thin.',
      'Divide evenly between pans and bake 30-35 minutes.',
      'Cool 10 minutes in pans, then turn out onto racks.',
      'Once fully cool, frost generously with chocolate ganache or buttercream.',
    ],
  },
  {
    id: 'sample-3',
    title: 'Brown Butter Chocolate Chip Cookies',
    category: 'Cookies',
    image_url: null,
    description: 'Chewy cookies with crispy edges. Brown butter adds a nutty, caramel-like depth.',
    time_minutes: 30,
    difficulty: 'Easy',
    user_id: 'sample',
    created_at: new Date().toISOString(),
    ingredients: [
      '1 cup (2 sticks) unsalted butter',
      '1¼ cups packed brown sugar',
      '¼ cup granulated sugar',
      '2 large eggs',
      '2 tsp pure vanilla extract',
      '2¼ cups all-purpose flour',
      '1 tsp baking soda',
      '1 tsp fine salt',
      '2 cups chocolate chips',
    ],
    instructions: [
      'Brown butter in a saucepan over medium heat until golden and nutty-smelling. Cool 15 min.',
      'Whisk in both sugars until fully combined.',
      'Beat in eggs and vanilla until mixture is smooth and glossy.',
      'Fold in flour, baking soda, and salt until just combined.',
      'Stir in chocolate chips.',
      'Chill dough 1 hour (or overnight for deeper flavour).',
      'Scoop onto lined baking sheets and bake at 375°F for 10-12 minutes — edges set, centres soft.',
    ],
  },
  {
    id: 'sample-4',
    title: 'Artisan Sourdough Loaf',
    category: 'Bread',
    image_url: null,
    description: 'Crusty artisan sourdough with a chewy open crumb. Worth every minute.',
    time_minutes: 240,
    difficulty: 'Hard',
    user_id: 'sample',
    created_at: new Date().toISOString(),
    ingredients: [
      '500g bread flour',
      '350g filtered water (room temp)',
      '100g active sourdough starter',
      '10g fine sea salt',
    ],
    instructions: [
      'Mix flour and 330g water. Rest 30 minutes (autolyse).',
      'Add starter and salt; squeeze through fingers until fully incorporated.',
      'Perform 4 sets of stretch-and-folds every 30 minutes.',
      'Bulk ferment at room temperature 4-6 hours until dough has risen ~75%.',
      'Shape gently into a round or oval and place seam-side-up in a floured banneton.',
      'Cold-proof in the fridge overnight (8-16 hours).',
      'Bake in a Dutch oven at 500°F — 20 min covered, 25 min uncovered — until deep golden.',
    ],
  },
  {
    id: 'sample-5',
    title: 'New York-Style Cheesecake',
    category: 'Cheesecake',
    image_url: null,
    description: 'Dense, creamy cheesecake on a buttery graham cracker crust. Refrigerate overnight for best results.',
    time_minutes: 90,
    difficulty: 'Medium',
    user_id: 'sample',
    created_at: new Date().toISOString(),
    ingredients: [
      '2 cups graham cracker crumbs',
      '½ cup melted butter',
      '3 packages (8oz each) cream cheese, softened',
      '1 cup granulated sugar',
      '3 large eggs',
      '1 tsp pure vanilla extract',
      '¼ cup sour cream',
      '2 tbsp all-purpose flour',
    ],
    instructions: [
      'Mix crumbs and butter; press firmly into base of 9-inch springform pan.',
      'Beat cream cheese and sugar until completely smooth and fluffy.',
      'Add eggs one at a time, mixing on low speed.',
      'Blend in vanilla, sour cream, and flour.',
      'Pour over crust and smooth the top.',
      'Bake at 325°F for 55 minutes — centre should have a slight wobble.',
      'Turn oven off, crack door open, cool 1 hour inside. Refrigerate overnight before serving.',
    ],
  },
  {
    id: 'sample-6',
    title: 'Classic French Croissants',
    category: 'Pastries',
    image_url: null,
    description: 'Flaky, golden croissants with hundreds of buttery layers. A weekend labour of love.',
    time_minutes: 360,
    difficulty: 'Hard',
    user_id: 'sample',
    created_at: new Date().toISOString(),
    ingredients: [
      '4 cups bread flour',
      '1 tbsp granulated sugar',
      '2 tsp fine salt',
      '2¼ tsp active dry yeast',
      '1½ cups whole milk, lukewarm',
      '2 cups cold unsalted butter (for lamination)',
      '1 egg + 1 tbsp milk (egg wash)',
    ],
    instructions: [
      'Combine flour, sugar, salt, yeast, and milk. Knead briefly until smooth. Wrap and chill overnight.',
      'Pound cold butter into an 8-inch square. Keep chilled.',
      'Encase butter in dough and complete 3 letter folds, chilling 30 min between each.',
      'Roll out to ¼-inch thick; cut into long triangles.',
      'Roll triangles tightly from base to tip; curl ends slightly.',
      'Proof at room temperature 2-3 hours until visibly puffy and jiggle gently.',
      'Brush with egg wash and bake at 400°F for 18-22 minutes until deeply golden.',
    ],
  },
]
